#!/usr/bin/env python3
"""
Build a static site for GitHub Pages from the per-fragment records.

Why this exists: the reports in 05_output/descriptors/ already run in a browser,
but they cannot be published as they stand, for two independent reasons.

  1. The .glb and _texture.png are tracked by Git LFS, and GitHub Pages does not
     resolve LFS. It serves the pointer file, so the viewer would fetch ~130
     bytes of text instead of a mesh.
  2. The twelve meshes and textures come to about 1.2 GB, against a 1 GB limit
     on a published Pages site, and a single fragment is 109 MB, which is not a
     reasonable download for a web viewer.

So this writes web-sized copies into docs/, which is NOT LFS-tracked (see
docs/.gitattributes). The report HTML is copied unchanged: it references its two
assets by relative filename, so replacing them with smaller files of the same
name is all that is required.

The landing page is the pipeline's own Material Inventory, copied from
05_output/descriptors/index.html with one note prepended. The published site and
the local tool therefore show the same interface.

The full-resolution meshes and textures stay in 05_output/ as the research data.
The site is a viewer, not the dataset.

    python 03_src/build_web.py
    python 03_src/build_web.py --faces 60000 --texture 2048
"""

import argparse
import gc
import re
import os
import shutil
import sys
import time
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SRC = REPO_ROOT / "05_output" / "descriptors"
DOCS = REPO_ROOT / "docs"

TARGET_FACES = 45_000     # web-viewer fidelity; the source meshes run to ~1.9 M
TEXTURE_MAX = 1024        # px on the long side


def build_fragment(frag: str, target_faces: int, tex_max: int) -> dict:
    """Write one web-sized GLB + texture + report. Returns a summary dict."""
    import numpy as np
    import trimesh
    import fast_simplification as fs
    from scipy.spatial import cKDTree
    from PIL import Image
    Image.MAX_IMAGE_PIXELS = None

    glb_in = SRC / f"{frag}.glb"
    tex_in = SRC / f"{frag}_texture.png"
    html_in = SRC / f"{frag}_report.html"
    if not (glb_in.exists() and tex_in.exists() and html_in.exists()):
        return {"fragment": frag, "skipped": "missing source files"}

    mesh = trimesh.load(glb_in, force="mesh", process=False)
    V = np.asarray(mesh.vertices)
    F = np.asarray(mesh.faces)
    UV = np.asarray(mesh.visual.uv)
    n_in = len(F)

    reduction = max(0.0, min(0.99, 1.0 - target_faces / n_in))
    if reduction > 0.01:
        Vd, Fd = fs.simplify(V, F, target_reduction=reduction)
        # UVs are per-vertex. Decimation makes new vertices, so each one takes
        # the UV of the nearest original vertex. Approximate, and indetectable
        # at this face count and texture size.
        UVd = UV[cKDTree(V).query(Vd, k=1)[1]]
    else:
        Vd, Fd, UVd = V, F, UV

    img = Image.open(tex_in).convert("RGB")
    img.thumbnail((tex_max, tex_max), Image.LANCZOS)

    out = trimesh.Trimesh(
        vertices=Vd, faces=Fd, process=False,
        visual=trimesh.visual.TextureVisuals(uv=UVd, image=img))
    out.export(DOCS / f"{frag}.glb")
    img.save(DOCS / f"{frag}_texture.png", optimize=True)
    shutil.copy2(html_in, DOCS / f"{frag}_report.html")

    # read the counts before freeing; these arrays are large
    n_out = len(Fd)
    del mesh, V, F, UV, Vd, Fd, UVd, out, img
    gc.collect()

    return {
        "fragment": frag,
        "faces_in": n_in,
        "faces_out": n_out,
        "glb_mb": round((DOCS / f"{frag}.glb").stat().st_size / 1e6, 2),
        "src_mb": round(glb_in.stat().st_size / 1e6, 1),
    }


# Added to the inventory when it is published, for readers who arrive at the site
# without the README. Inline styles only: the inventory's own CSS is generated by
# report.py and this must not depend on a class name defined over there.
PUBLIC_NOTE = """
  <div style="max-width:78ch;margin:0 0 22px;padding:12px 16px;
              border-left:3px solid #c98a2e;background:#fdf7ec;color:#5a4a2e;
              font-size:13.5px;line-height:1.55">
    <strong>Surface labels on this site are provisional.</strong>
    The classifier was scored against two hand-labelled tile sets and does not exceed a
    null model that answers the two commonest features and looks at nothing. The geometric
    descriptors are computed deterministically and are verified. A <code>rebar_visible</code>
    negative is absent evidence, not evidence of absence, and is not drilling guidance.
    Models in the 3D viewers are decimated for the browser; the full-resolution meshes are
    archived separately. Evaluation and sources:
    <a href="https://github.com/muchenykadk/study2-descriptor-pipeline">repository README</a>.
  </div>"""


def publish_inventory() -> None:
    """Publish the pipeline's own inventory page as the site landing page.

    The inventory that report.update_inventory() writes is the interface this
    project actually has: the fragment table, the filters, and the record fields.
    An earlier version of this function generated a substitute card grid instead,
    which silently dropped all of that and shipped a different, poorer page than
    the one running locally. The site must show the same interface as the tool.

    The only change made on the way out is PUBLIC_NOTE, because a visitor arriving
    at the URL has not read the README and needs the status of the labels stated
    on the page they land on.
    """
    src = SRC / "index.html"
    if not src.exists():
        raise SystemExit(
            f"\n  {src.relative_to(REPO_ROOT)} does not exist. Run the pipeline, or\n"
            f"  python 03_src/refresh_factors.py --reports-only, to generate it.\n")

    html = src.read_text(encoding="utf-8")

    # The inventory embeds the records verbatim, and each region record carries an
    # `image_path` written as an absolute path on the machine that ran the pipeline.
    # That would publish the author's home directory on a public page. Cut the prefix
    # so the path reads from the repository root, which is what a reader can act on.
    # The records themselves still hold the absolute form; fixing that belongs where
    # image_path is written, not here.
    html, n = re.subn(r'[A-Za-z]:\\{1,2}[^"]*?Study2_Descriptor_Pipeline\\{1,2}', "", html)
    if n:
        print(f"  stripped {n} absolute local path(s) from the inventory")

    anchor = "<h1>Material Inventory</h1>"
    if anchor in html:
        html = html.replace(anchor, anchor + PUBLIC_NOTE, 1)
    elif "<body>" in html:
        html = html.replace("<body>", "<body>" + PUBLIC_NOTE, 1)
    else:
        print("  ! could not place the public note; publishing the inventory unchanged")

    (DOCS / "index.html").write_text(html, encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--faces", type=int, default=TARGET_FACES)
    ap.add_argument("--texture", type=int, default=TEXTURE_MAX)
    ap.add_argument("--only", default="", help="one fragment id, for testing")
    args = ap.parse_args()

    DOCS.mkdir(exist_ok=True)
    # Undo the repository-wide LFS rules for this folder. GitHub Pages cannot
    # serve LFS objects, so everything here must be a real file in git.
    (DOCS / ".gitattributes").write_text(
        "# GitHub Pages does not resolve Git LFS, so these must be plain files.\n"
        "*.glb -filter -diff -merge text=auto\n"
        "*.png -filter -diff -merge text=auto\n"
        "*.glb binary\n*.png binary\n", encoding="utf-8")
    (DOCS / ".nojekyll").write_text("", encoding="utf-8")

    frags = ([args.only] if args.only else
             sorted(p.stem for p in SRC.glob("FRAG-*.glb")))
    rows, t0 = [], time.time()
    for i, f in enumerate(frags, 1):
        t = time.time()
        r = build_fragment(f, args.faces, args.texture)
        if "skipped" in r:
            print(f"  [{i}/{len(frags)}] {f}: {r['skipped']}")
            continue

        rows.append(r)
        print(f"  [{i}/{len(frags)}] {f}: {r['faces_in']:,} → {r['faces_out']:,} faces, "
              f"{r['src_mb']} → {r['glb_mb']} MB  ({time.time()-t:.0f}s)")

    publish_inventory()
    total = sum(p.stat().st_size for p in DOCS.rglob("*") if p.is_file())
    print(f"\n  {len(rows)} fragments -> {DOCS.relative_to(REPO_ROOT)}/  "
          f"{total/1e6:.0f} MB total, {time.time()-t0:.0f}s")
    print(f"  index: docs/index.html")


if __name__ == "__main__":
    main()
