#!/usr/bin/env python3
"""
Re-derive the design factors on existing records, without re-running the pipeline.

The design factors in `env/design_factors.json` are meant to be tuned: thresholds
for handling class, connection strategy, and the candidate uses will change as
they are tested against real fragments.  Re-running the whole pipeline for that
would recompute geometry and re-issue vision calls for no reason.

This reads each `*_geometry.json`, re-runs the factors over the descriptors
already in it, rewrites the record, and regenerates the inventory page.  No
geometry is recomputed and no API call is made.

    python 03_src/refresh_factors.py            # all records
    python 03_src/refresh_factors.py --dry-run  # show what would change
"""

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "03_src"))

from descriptors.design_factors import derive as derive_design_factors
from report import update_inventory

DEFAULT_DIR = REPO_ROOT / "05_output" / "descriptors"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--records-dir", default=str(DEFAULT_DIR))
    ap.add_argument("--dry-run", action="store_true",
                    help="report the change without writing the records")
    args = ap.parse_args()

    records_dir = Path(args.records_dir)
    paths = sorted(records_dir.glob("*_geometry.json"))
    if not paths:
        print(f"\n  No records in {records_dir}. Run the pipeline first.\n")
        sys.exit(1)

    print()
    for p in paths:
        rec = json.loads(p.read_text(encoding="utf-8"))
        before = {u["id"] for u in
                  ((rec.get("procedural") or {}).get("use_suggestions") or [])}
        proc  = derive_design_factors(rec)
        after = {u["id"] for u in proc["use_suggestions"]}

        added, gone = sorted(after - before), sorted(before - after)
        change = ""
        if added:
            change += "  +" + ", +".join(added)
        if gone:
            change += "  -" + ", -".join(gone)
        if not before and not after:
            change = "  no candidate use"

        handling = (proc.get("handling_class") or {}).get("value") or "?"
        print(f"  {rec.get('fragment_id','?'):<18} {len(after)} use(s), "
              f"handling {handling}{change}")

        if not args.dry_run:
            p.write_text(json.dumps(rec, indent=2), encoding="utf-8")

    if args.dry_run:
        print("\n  dry run: nothing written.\n")
        return

    index = update_inventory(records_dir)
    try:
        shown = index.relative_to(REPO_ROOT)
    except ValueError:
        shown = index
    print(f"\n  {len(paths)} record(s) updated; inventory rebuilt at {shown}")
    print("  Note: the per-fragment HTML reports are regenerated by the "
          "pipeline, not here.\n")


if __name__ == "__main__":
    main()
